// Comprehensive inventory of every entity in src/types/*.ts with its accounting metadata.
// Source of truth for skill 39 (auditdataflow-completeness-audit).
// 4 columns per entity: source → voucher → CoA leaf → audit consumer.

export type CashAccrualTreatment = "accrual" | "cash" | "both" | "n/a";
export type PostingNature = "asset" | "liability" | "income" | "expense" | "capital" | "non-financial";

export interface EntityPostingRow {
  entity: string;
  /** Where the data lives in `src/types/*.ts`. */
  typesFile: string;
  /** What event creates an accounting entry. */
  trigger: string;
  /** Plain-English description of the debit + credit pair, OR "n/a" for non-financial entities. */
  voucher: string;
  /** Comma-joined CoA leaf values affected. */
  coaLeaves: string;
  /** Where this entity surfaces in the audit module set. */
  auditConsumer: string;
  cashAccrual: CashAccrualTreatment;
  gstImpact: string;
  notes?: string;
}

export const ENTITY_POSTING_INVENTORY: EntityPostingRow[] = [
  // ============== SALES SIDE ==============
  {
    entity: "Invoice",
    typesFile: "finance.ts",
    trigger: "On creation (non-draft)",
    voucher: "Debit Sundry Debtors · Credit Sales Accounts + GST Output Payable",
    coaLeaves: "sundry-debtors, solar-system-sales / service-income, gst-output-payable",
    auditConsumer: "P&L Revenue, Debtors, GST Compliance (GSTR-1)",
    cashAccrual: "accrual",
    gstImpact: "Output GST accrues; CGST+SGST intra-state, IGST inter-state",
  },
  {
    entity: "SaleBill",
    typesFile: "finance.ts",
    trigger: "On creation",
    voucher: "Debit Sundry Debtors · Credit Material Sales + GST Output Payable",
    coaLeaves: "sundry-debtors, material-sales, gst-output-payable",
    auditConsumer: "P&L Revenue, Debtors, GST Compliance (B2C)",
    cashAccrual: "accrual",
    gstImpact: "Same as Invoice",
  },
  {
    entity: "Payment",
    typesFile: "finance.ts",
    trigger: "On receipt from customer (direction=in)",
    voucher: "Debit Cash/Bank · Credit Sundry Debtors (or Advances from Customers if no invoice)",
    coaLeaves: "cash-in-hand / bank-accounts, sundry-debtors / advances-from-customers",
    auditConsumer: "Cash & Bank Ledger, Debtors (reduces), Receipts register",
    cashAccrual: "cash",
    gstImpact: "n/a (already accrued on invoice)",
    notes: "When paymentSource=partner (W5): pair with PartnerTransaction(Customer Paid Partner)",
  },
  {
    entity: "VendorBill",
    typesFile: "finance.ts",
    trigger: "On creation",
    voucher: "Debit Purchase Accounts (or Indirect Expense) + GST Input Credit · Credit Sundry Creditors",
    coaLeaves: "material-purchases / sub-contract-charges / indirect leaves, gst-input-credit, sundry-creditors",
    auditConsumer: "P&L COGS or Indirect, Creditors, GST Compliance (GSTR-2A)",
    cashAccrual: "accrual",
    gstImpact: "Input ITC accrues if vendor registered + item not in blocked list",
  },
  {
    entity: "VendorPayment",
    typesFile: "finance.ts",
    trigger: "On payment to vendor",
    voucher: "Debit Sundry Creditors · Credit Cash/Bank (less TDS Payable if applicable)",
    coaLeaves: "sundry-creditors, cash-in-hand / bank-accounts, tds-payable",
    auditConsumer: "Cash & Bank Ledger, Creditors (reduces)",
    cashAccrual: "cash",
    gstImpact: "n/a",
  },

  // ============== EXPENSES & INCOME ==============
  {
    entity: "Expense",
    typesFile: "finance.ts",
    trigger: "Per expenseToAccountMapping",
    voucher: "Debit (per CoA leaf) · Credit Cash/Bank (or Payable per payerType)",
    coaLeaves: "varies per (main, sub) — see expenseToAccountMapping master",
    auditConsumer: "P&L (line per plLine), Expense Audit, Cash & Bank Ledger",
    cashAccrual: "cash",
    gstImpact: "Per gstTreatment column in mapping",
  },
  {
    entity: "Income",
    typesFile: "finance.ts",
    trigger: "Per incomeToAccountMapping",
    voucher: "Debit Cash/Bank · Credit (per CoA leaf — Sales / Capital / Liability)",
    coaLeaves: "cash-in-hand / bank-accounts, varies per mapping",
    auditConsumer: "P&L Revenue (if revenue) OR Liability movement OR Capital",
    cashAccrual: "cash",
    gstImpact: "Per gstTreatment in mapping",
  },

  // ============== CAPITAL ==============
  {
    entity: "OwnerInvestment (type=investment)",
    typesFile: "finance.ts",
    trigger: "On owner contribution",
    voucher: "Debit Cash/Bank · Credit Owner Capital",
    coaLeaves: "cash-in-hand / bank-accounts, owner-capital",
    auditConsumer: "Capital Account (Balance Sheet)",
    cashAccrual: "cash",
    gstImpact: "n/a",
    notes: "EXCLUDED from P&L (capital, not income)",
  },
  {
    entity: "OwnerInvestment (type=withdrawal)",
    typesFile: "finance.ts",
    trigger: "On owner drawing",
    voucher: "Debit Owner Drawings · Credit Cash/Bank",
    coaLeaves: "owner-drawings, cash-in-hand / bank-accounts",
    auditConsumer: "Capital Account (Drawings)",
    cashAccrual: "cash",
    gstImpact: "n/a",
    notes: "EXCLUDED from P&L (reduces Capital, not expense)",
  },

  // ============== LOANS ==============
  {
    entity: "Loan (disbursement)",
    typesFile: "finance.ts",
    trigger: "When loan funds arrive",
    voucher: "Debit Cash/Bank · Credit Secured/Unsecured/Vehicle Loans",
    coaLeaves: "cash-in-hand / bank-accounts, secured-loans / unsecured-loans / vehicle-loans",
    auditConsumer: "Liability schedule, Debtors-Creditors",
    cashAccrual: "cash",
    gstImpact: "n/a",
  },
  {
    entity: "LoanRepayment",
    typesFile: "finance.ts",
    trigger: "On EMI / part-payment",
    voucher: "SPLIT: Debit Loan Interest (P&L Finance) + Debit Loan Liability · Credit Cash/Bank",
    coaLeaves: "loan-interest, secured-loans / unsecured-loans / vehicle-loans, cash-in-hand / bank-accounts",
    auditConsumer: "P&L Finance Cost (interest only), Loan schedule (principal)",
    cashAccrual: "cash",
    gstImpact: "n/a",
    notes: "Principal NOT in P&L — reduces loan liability only",
  },

  // ============== PARTNER ==============
  {
    entity: "Partner",
    typesFile: "finance.ts",
    trigger: "On partner creation",
    voucher: "n/a (master entity)",
    coaLeaves: "—",
    auditConsumer: "—",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "PartnerTransaction (Given to Partner)",
    typesFile: "finance.ts",
    trigger: "Cash given to partner",
    voucher: "Debit Partner Drawings (or Partner Receivable) · Credit Cash/Bank",
    coaLeaves: "partner-drawings / partner-receivable, cash-in-hand / bank-accounts",
    auditConsumer: "Partner ledger, Capital Account",
    cashAccrual: "cash",
    gstImpact: "n/a",
  },
  {
    entity: "PartnerTransaction (Received from Partner)",
    typesFile: "finance.ts",
    trigger: "Cash received from partner",
    voucher: "Debit Cash/Bank · Credit Partner Drawings (or Partner Receivable reduction)",
    coaLeaves: "cash-in-hand / bank-accounts, partner-drawings / partner-receivable",
    auditConsumer: "Partner ledger",
    cashAccrual: "cash",
    gstImpact: "n/a",
  },
  {
    entity: "PartnerTransaction (Customer Paid Partner)",
    typesFile: "finance.ts",
    trigger: "Client paid partner instead of us (W5)",
    voucher: "Debit Partner Receivable · Credit Sundry Debtors (invoice settled)",
    coaLeaves: "partner-receivable, sundry-debtors",
    auditConsumer: "Partner ledger, Debtors (reduces)",
    cashAccrual: "cash",
    gstImpact: "n/a (output GST already accrued on invoice)",
    notes: "Pair with Payment(paymentSource=partner) so project.amountReceived increments",
  },
  {
    entity: "PartnerTransaction (Profit Payment)",
    typesFile: "finance.ts",
    trigger: "MSS pays partner their profit share",
    voucher: "Debit Partner Drawings · Credit Cash/Bank",
    coaLeaves: "partner-drawings, cash-in-hand / bank-accounts",
    auditConsumer: "Capital Account (Partner Drawings)",
    cashAccrual: "cash",
    gstImpact: "n/a",
    notes: "EXCLUDED from P&L (reduces Partner Capital)",
  },
  {
    entity: "PartnerTransaction (Vendorship Fee)",
    typesFile: "finance.ts",
    trigger: "Partner pays MSS to use our vendorship code",
    voucher: "Debit Cash/Bank · Credit Vendorship Fee Income + GST Output Payable",
    coaLeaves: "cash-in-hand / bank-accounts, vendorship-fee-income, gst-output-payable",
    auditConsumer: "P&L Revenue, GST Compliance",
    cashAccrual: "cash",
    gstImpact: "Output GST applies",
  },
  {
    entity: "PartnerSiteInvestment",
    typesFile: "finance.ts",
    trigger: "Partner invests in a specific site",
    voucher: "Debit Cash/Bank (site) · Credit Partner Capital",
    coaLeaves: "cash-in-hand / bank-accounts, partner-capital",
    auditConsumer: "Capital Account",
    cashAccrual: "cash",
    gstImpact: "n/a",
  },

  // ============== INVENTORY & TOOLS ==============
  {
    entity: "InventoryItem",
    typesFile: "project.ts",
    trigger: "Master entity (no entry on create)",
    voucher: "n/a until movement / damage",
    coaLeaves: "stock-in-hand (balance computed)",
    auditConsumer: "Inventory Audit, Balance Sheet",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "InventoryMovementRecord (purchase)",
    typesFile: "project.ts",
    trigger: "On stock purchase (via VendorBill)",
    voucher: "Debit Stock-in-Hand · Credit Sundry Creditors (via VendorBill)",
    coaLeaves: "stock-in-hand, sundry-creditors",
    auditConsumer: "Inventory Audit (WAC running)",
    cashAccrual: "accrual",
    gstImpact: "Input ITC via VendorBill",
  },
  {
    entity: "InventoryMovementRecord (issue-to-site)",
    typesFile: "project.ts",
    trigger: "On material issue",
    voucher: "Debit Work-in-Progress (or COGS at invoice time) · Credit Stock-in-Hand",
    coaLeaves: "(deferred WIP), stock-in-hand",
    auditConsumer: "Inventory Audit",
    cashAccrual: "n/a",
    gstImpact: "n/a",
    notes: "NO P&L impact at issue — relieved as COGS only when project invoiced",
  },
  {
    entity: "InventoryMovementRecord (return)",
    typesFile: "project.ts",
    trigger: "On return from site",
    voucher: "Debit Stock-in-Hand · Credit WIP (reverse issue)",
    coaLeaves: "stock-in-hand",
    auditConsumer: "Inventory Audit",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "InventoryMovementRecord (reverse)",
    typesFile: "project.ts",
    trigger: "Super-admin manual reversal",
    voucher: "Undo the original entry at the same WAC",
    coaLeaves: "(varies per original)",
    auditConsumer: "Inventory Audit, Audit Logs",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "MaterialDamage",
    typesFile: "project.ts",
    trigger: "Damage report",
    voucher: "Debit Material Damage Written-off · Credit Stock-in-Hand",
    coaLeaves: "site-damages-written-off, stock-in-hand",
    auditConsumer: "P&L Direct (COGS), Inventory Audit",
    cashAccrual: "accrual",
    gstImpact: "Reverse Input ITC if claimed",
  },
  {
    entity: "ProcurementNeedLine",
    typesFile: "operations.ts",
    trigger: "Need-to-get shortfall assigned to vendor",
    voucher: "n/a (procurement commitment)",
    coaLeaves: "—",
    auditConsumer: "Inventory Audit, vendor acquire tab",
    cashAccrual: "n/a",
    gstImpact: "n/a",
    notes: "Links site/material to vendor before VendorBill posting",
  },
  {
    entity: "MaterialReservation",
    typesFile: "operations.ts",
    trigger: "Reservation made",
    voucher: "n/a (commitment, not entry)",
    coaLeaves: "—",
    auditConsumer: "Inventory Audit (committed qty)",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "Tool",
    typesFile: "project.ts",
    trigger: "On purchase",
    voucher: "Debit Tools & Equipment (Gross) · Credit Sundry Creditors (via VendorBill)",
    coaLeaves: "tools-equipment-gross, sundry-creditors",
    auditConsumer: "Fixed Assets register",
    cashAccrual: "accrual",
    gstImpact: "Input ITC eligible",
  },
  {
    entity: "ToolMovementRecord",
    typesFile: "project.ts",
    trigger: "Issue/return tool",
    voucher: "n/a (location change, not value)",
    coaLeaves: "—",
    auditConsumer: "Fixed Assets register",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "Tool (depreciation)",
    typesFile: "project.ts",
    trigger: "Year-end / period-end",
    voucher: "Debit Depreciation · Credit Accumulated Depreciation",
    coaLeaves: "depreciation, accumulated-depreciation",
    auditConsumer: "P&L Indirect, Fixed Assets",
    cashAccrual: "accrual",
    gstImpact: "n/a",
  },

  // ============== HR ==============
  {
    entity: "Employee",
    typesFile: "project.ts",
    trigger: "Master entity (no entry on create)",
    voucher: "n/a",
    coaLeaves: "—",
    auditConsumer: "—",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "EmployeePayrollRecord",
    typesFile: "project.ts",
    trigger: "On salary release",
    voucher: "Debit Salaries (office or direct) · Credit Cash/Bank (less TDS Payable if applicable)",
    coaLeaves: "salaries-office / direct-labour, cash-in-hand / bank-accounts, tds-payable",
    auditConsumer: "P&L Indirect or Direct, Cash & Bank Ledger",
    cashAccrual: "cash",
    gstImpact: "n/a (employees not GST registered)",
  },
  {
    entity: "AttendanceRecord",
    typesFile: "project.ts",
    trigger: "Daily attendance",
    voucher: "n/a (informational; feeds payroll calc)",
    coaLeaves: "—",
    auditConsumer: "Payroll, Audit Logs",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "Holiday",
    typesFile: "project.ts",
    trigger: "Paid-holiday marker",
    voucher: "n/a (feeds payroll)",
    coaLeaves: "—",
    auditConsumer: "Payroll",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "EmployeeWalletLedgerEntry",
    typesFile: "project.ts",
    trigger: "Advance / recovery",
    voucher: "Advance: Debit Employee Advance Receivable · Credit Cash/Bank. Recovery: reverse.",
    coaLeaves: "employee-advance-receivable, cash-in-hand / bank-accounts",
    auditConsumer: "Debtors (Employee Advance), Cash & Bank Ledger",
    cashAccrual: "cash",
    gstImpact: "n/a",
  },
  {
    entity: "Team",
    typesFile: "project.ts",
    trigger: "Master entity",
    voucher: "n/a",
    coaLeaves: "—",
    auditConsumer: "—",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "Task",
    typesFile: "project.ts",
    trigger: "Operational entity",
    voucher: "n/a (no direct accounting)",
    coaLeaves: "—",
    auditConsumer: "Audit Logs",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },

  // ============== AGENTS ==============
  {
    entity: "Agent",
    typesFile: "finance.ts",
    trigger: "Master entity",
    voucher: "n/a",
    coaLeaves: "—",
    auditConsumer: "—",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "AgentCommissionAccrual",
    typesFile: "finance.ts",
    trigger: "When project status moves to ongoing",
    voucher: "Debit Sub-contract Charges (or Sales Commission) · Credit Agent Commission Payable",
    coaLeaves: "sub-contract-charges, outstanding-expenses (agent-commission bucket)",
    auditConsumer: "P&L Direct, Creditors (Agent Commission)",
    cashAccrual: "accrual",
    gstImpact: "Per agent's registration (ITC if registered + TDS deduction if applicable)",
  },
  {
    entity: "AgentCommissionPayment",
    typesFile: "finance.ts",
    trigger: "When commission paid",
    voucher: "Debit Agent Commission Payable · Credit Cash/Bank (less TDS if applicable)",
    coaLeaves: "outstanding-expenses (commission bucket), cash-in-hand / bank-accounts, tds-payable",
    auditConsumer: "Cash & Bank Ledger, Creditors (reduces)",
    cashAccrual: "cash",
    gstImpact: "n/a (already accrued on accrual entry)",
  },

  // ============== INC / VENDORSHIP ==============
  {
    entity: "INCGiverCompany",
    typesFile: "finance.ts",
    trigger: "Master entity",
    voucher: "n/a",
    coaLeaves: "—",
    auditConsumer: "—",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "INCGiverTransaction",
    typesFile: "finance.ts",
    trigger: "INC source pays / charges fee",
    voucher: "Per direction — fee debit: Carriage Inward; fee credit: Other Income",
    coaLeaves: "carriage-inward / other-operating-income",
    auditConsumer: "P&L Direct or Other Income",
    cashAccrual: "cash",
    gstImpact: "ITC eligible if registered",
  },
  {
    entity: "VendorshipCompany",
    typesFile: "finance.ts",
    trigger: "Master entity",
    voucher: "n/a",
    coaLeaves: "—",
    auditConsumer: "—",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },

  // ============== CRM / SALES ==============
  {
    entity: "Customer",
    typesFile: "finance.ts",
    trigger: "Master entity",
    voucher: "n/a",
    coaLeaves: "—",
    auditConsumer: "—",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "Vendor",
    typesFile: "project.ts",
    trigger: "Master entity",
    voucher: "n/a",
    coaLeaves: "—",
    auditConsumer: "—",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "Enquiry",
    typesFile: "enquiry.ts",
    trigger: "Pre-financial; CRM entity",
    voucher: "n/a",
    coaLeaves: "—",
    auditConsumer: "—",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "Quotation",
    typesFile: "project.ts",
    trigger: "Pre-financial; converts to invoice",
    voucher: "n/a (until accepted → linked to Project + Invoice)",
    coaLeaves: "—",
    auditConsumer: "Audit Logs",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "Project",
    typesFile: "project.ts",
    trigger: "Operational entity (financial via linked Invoice/Expense/etc.)",
    voucher: "n/a (aggregator)",
    coaLeaves: "—",
    auditConsumer: "Project P&L (custom view), Audit Logs",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "ProjectChangeRequest",
    typesFile: "project.ts",
    trigger: "Scope-change request",
    voucher: "n/a (until additional invoice raised)",
    coaLeaves: "—",
    auditConsumer: "Audit Logs, Project P&L",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "SiteRecord",
    typesFile: "project.ts",
    trigger: "Operational entity",
    voucher: "n/a",
    coaLeaves: "—",
    auditConsumer: "—",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "ScheduledInstallation",
    typesFile: "project.ts",
    trigger: "Planning entity",
    voucher: "n/a",
    coaLeaves: "—",
    auditConsumer: "Audit Logs",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "SiteVisit",
    typesFile: "project.ts",
    trigger: "Operational entity",
    voucher: "n/a (linked expense recorded separately)",
    coaLeaves: "—",
    auditConsumer: "Audit Logs",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "Blockage / Ticket",
    typesFile: "blockage.ts",
    trigger: "Operational entity",
    voucher: "n/a",
    coaLeaves: "—",
    auditConsumer: "Audit Logs",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
  {
    entity: "AccountingVoucher",
    typesFile: "finance.ts",
    trigger: "Manual journal entry (super-admin)",
    voucher: "Manual debit/credit pair to any CoA leaves",
    coaLeaves: "any",
    auditConsumer: "Chart of Accounts, Audit Logs",
    cashAccrual: "n/a",
    gstImpact: "Per entry",
  },
  {
    entity: "AccountingReviewQueueItem",
    typesFile: "finance.ts",
    trigger: "Auto-flagged unusual entry for super-admin review",
    voucher: "n/a (review-only)",
    coaLeaves: "—",
    auditConsumer: "Audit Logs, Chart of Accounts auto-posting rules",
    cashAccrual: "n/a",
    gstImpact: "n/a",
  },
];
