import type { ProjectKind } from "@/domain/projectTypes/types";

export type CreateProjectWizardSource = "new" | "quotation" | "direct_exception" | "attach_outsourced";
export type CreateProjectWizardLeadPath = "MSS_DIRECT" | "PARTNER" | "INC_GIVEN" | "OUTSOURCED_INC";
export type CreateProjectWizardPartnerType = "profit_share" | "fixed_rate" | "vendor_channel" | "vendorship_only";
export type CreateProjectWizardProjectType = "Residential" | "Commercial" | "Industrial";
export type CreateProjectWizardProjectCategory = "solar" | "other";
export type CreateProjectWizardPaymentType = "cash" | "loan" | "cash-and-loan";
export type CreateProjectWizardCustomerMode = "select" | "add";
export type CreateProjectWizardVendorshipChoice = "OUR_CODE" | "THIRD_PARTY";
export type CreateProjectWizardBillingParty = "MSS" | "PARTNER";
export type CreateProjectWizardIncScope = "labour" | "labour_and_materials";
export type CreateProjectWizardRateBasis = "per_kw" | "per_sqft" | "fixed";
export type CreateProjectWizardOutsourceMode = "existing" | "new";
export type WizardFlow = "intake" | "quotation" | "direct_exception" | "attach";
export type WizardStep = "SOURCE" | "LEAD_PATH" | "CUSTOMER" | "COMMERCIAL" | "VENDORSHIP" | "AGENT" | "TEAM" | "DEAL_TYPE" | "PARTIES" | "REVIEW" | "QUOTATION" | "EXCEPTION" | "ATTACH_PARTIES" | "OUTSOURCE_TERMS";
export const WIZARD_STEPS: WizardStep[] = ["SOURCE", "LEAD_PATH", "CUSTOMER", "COMMERCIAL", "VENDORSHIP", "AGENT", "TEAM", "DEAL_TYPE", "PARTIES", "REVIEW", "QUOTATION", "EXCEPTION", "ATTACH_PARTIES", "OUTSOURCE_TERMS"];
export const WIZARD_FLOW_STEPS = { intake: ["DEAL_TYPE","PARTIES","COMMERCIAL","REVIEW"], quotation: ["QUOTATION","REVIEW"], direct_exception: ["EXCEPTION","DEAL_TYPE","PARTIES","COMMERCIAL","REVIEW"], attach: ["ATTACH_PARTIES","OUTSOURCE_TERMS","REVIEW"] } as const;
export const WIZARD_STEP_LABELS = { SOURCE: "Source", LEAD_PATH: "Deal structure", CUSTOMER: "Customer", COMMERCIAL: "Commercial", VENDORSHIP: "Vendorship & GST", AGENT: "Agent", TEAM: "Team", DEAL_TYPE: "Deal structure", PARTIES: "Parties", REVIEW: "Review", QUOTATION: "Quotation", EXCEPTION: "Exception reason", ATTACH_PARTIES: "Project & subcontractor", OUTSOURCE_TERMS: "Outsource terms" } as const;
export interface CreateProjectWizardState { flow?: WizardFlow; source: CreateProjectWizardSource; selectedQuotationId?: string; directExceptionReason?: string; directExceptionProjectKind?: ProjectKind; attachToProjectId?: string; outsourceMode?: CreateProjectWizardOutsourceMode; leadPath?: CreateProjectWizardLeadPath; partnerType?: CreateProjectWizardPartnerType; customerMode?: CreateProjectWizardCustomerMode; selectedCustomerId?: string; newCustomerName?: string; newCustomerPhone?: string; newCustomerEmail?: string; newCustomerAddress?: string; location?: string; kNumber?: string; partnerCustomerName?: string; incGiverCompanyId?: string; incAddress?: string; selectedSubcontractorId?: string; outsourceRateBasis?: CreateProjectWizardRateBasis; outsourceRateValue?: number; outsourceQuantity?: number; outsourceNotes?: string; projectName?: string; partnerProjectName?: string; incProjectName?: string; projectType?: CreateProjectWizardProjectType; partnerProjectType?: CreateProjectWizardProjectType; projectCategory?: CreateProjectWizardProjectCategory; capacity?: string; partnerCapacity?: string; incCapacity?: string; incArea?: string; contractAmount?: number; partnerContractAmount?: number; internalCostEstimate?: number; paymentType?: CreateProjectWizardPaymentType; fundingLoanId?: string; selectedPartnerId?: string; profitSharePercent?: number; fixedRatePerKw?: number; backendPrice?: number; partnerSellPrice?: number; commissionRule?: string; vendorOrDiscom?: string; channelPartnerName?: string; externalNetworkName?: string; rateBasis?: CreateProjectWizardRateBasis; rateValue?: number; incRateInputs?: Record<string, number>; incFixedAmount?: number; incScope?: CreateProjectWizardIncScope; vendorshipChoice?: CreateProjectWizardVendorshipChoice; vendorshipCompanyId?: string; vendorshipFeeAmount?: number; partnerVendorshipChoice?: CreateProjectWizardVendorshipChoice; partnerThirdPartyCompanyId?: string; partnerVendorshipFeeAmount?: number; billingParty?: CreateProjectWizardBillingParty; partnerGstInvoice?: "yes" | "no"; selectedAgentId?: string; commissionRatePct?: number; primaryAssigneeId?: string; targetEndDate?: string; quotationEditDetails?: boolean; dealKind?: ProjectKind; }
export function createInitialCreateProjectWizardState(overrides?: Partial<CreateProjectWizardState>): CreateProjectWizardState { return { source: "new", customerMode: "select", vendorshipChoice: "OUR_CODE", partnerVendorshipChoice: "OUR_CODE", billingParty: "MSS", partnerGstInvoice: "yes", outsourceMode: "existing", projectCategory: "solar", projectType: "Residential", partnerProjectType: "Residential", rateBasis: "per_kw", outsourceRateBasis: "fixed", ...overrides }; }
